{% set name = "pygeodesic" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeodesic-{{ version }}.tar.gz
  sha256: 56b73149ad15fdb88cab905486c178cb3a918f59fa2eb65705a19e22644573b8
  patches:
    - ptr.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython >=3
    - numpy
    - pip
    - python
    - setuptools >=42
    - wheel >=0.33.0
  run:
    - {{ pin_compatible('numpy') }}
    - python

test:
  imports:
    - pygeodesic
  commands:
    - pip list
    - pip check
  requires:
    - pip
  files:
    - flat_triangular_mesh.txt

about:
  home: https://pypi.org/project/pygeodesic
  summary: Python library for calculating geodesic distance on triangular based surface meshes
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mhogg/pygeodesic

extra:
  recipe-maintainers:
    - goanpeca
